export const DELIVERY_CITIES = 'DELIVERY_CITIES';
export const DELIVERY_STREETS = 'DELIVERY_STREETS';
export const DELIVERY_WAREHOUSES = 'DELIVERY_WAREHOUSES';
export const DELIVERY_PRICE = 'DELIVERY_PRICE';
export const DELIVERY_FAILS = 'DELIVERY_FAILS';
export const DELIVERY_ORDER_NUMBER = 'DELIVERY_ORDER_NUMBER';
export const DELIVERY_LOADING = 'DELIVERY_LOADING';
export const DELIVERY_TYPES = {
    WAREHOUSE_WAREHOUSE: 'WarehouseWarehouse',
    WAREHOUSE_DOORS: 'WarehouseDoors',
    SELF_PICKUP: 'SelfPickup',
}
